### ISSUE TITLE
[machineset chart on aro] publicLoadBalancer should be optional

### ISSUE THREAD

**Issue by davidkarlsen** [rh-mobb/helm-charts#62]
If you are running a private cluster: https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x - there won't be a loadbalancer  - hence this field should be conditional on actually specifying a publicLoadBalancer value.

**Comment by davidkarlsen** [comment]
wdyt @paulczar ? I can create a PR if you think it is a good idea.

**Comment by davidkarlsen** [comment]
Got it to work with these values:
```yaml
  machineSetSpec:
          location: norwayeast
          networkResourceGroup: network-nore-rg
          resourceGroup: aro-ftm-aro-dev-nore-rg
          subnet: ftm-aro-dev-worker-snet
          publicLoadBalancer: '' <--
```
